baseurl = "https://knowsuchagency.github.io"
languageCode = "en-us"
title = "Journal Panic"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
canonifyURLs = true


[Params]
  subtitle = "Makefiles not war"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  name = "Stephan Fitzpatrick"
  email = "knowsuchagency@gmail.com"
  facebook = "stephan.fitzpatrick"
  github = "knowsuchagency"
  twitter = "knowsuchagency"
  linkedin = "fitzpatrickstephan"
  stackoverflow = "users/5933618/stephan-fitzpatrick"
  instagram = "knowsuchagency"
  youtube = "user/knowsuchagency"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Resume"
    url = "/page/resume/"
    weight = 4