baseurl = "https://knowsuchagency.github.io"
languageCode = "en-us"
title = "Journal Panic"
theme = "beautifulhugo"
pygmentsuseclasses = true
PygmentsCodeFences = true
disqusShortname = "journal-panic"
#googleAnalytics = "UA-92708915-1"
canonifyURLs = true


[Params]
  subtitle = "Makefiles Not War"
  logo = "img/lambda.png"
  favicon = "img/lambda.ico"
  commit = false
  topmenu="categories"

[Author]
  name = "Stephan Fitzpatrick"
  email = "knowsuchagency@gmail.com"
  facebook = "stephan.fitzpatrick"
  github = "knowsuchagency"
  twitter = "knowsuchagency"
  linkedin = "fitzpatrickstephan"
  stackoverflow = "users/5933618/stephan-fitzpatrick"
  instagram = "knowsuchagency"
  # youtube = "user/knowsuchagency"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Resume"
    url = "/page/resume/"
    weight = 4

[[menu.main]]
    name = "Projects"
    url = "/page/projects/"
    weight = 4